# Generated by Django 3.0.7 on 2020-06-16 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('cat_slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_description', models.TextField(max_length=500)),
                ('pro_condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100)),
                ('pro_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pro_image', models.ImageField(blank=True, null=True, upload_to='main_product/')),
                ('pro_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('pro_slug', models.SlugField(blank=True, null=True)),
                ('category_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resale.Category')),
                ('pro_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resale.Brand')),
                ('pro_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proimg_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_productimages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resale.Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
