# Generated by Django 3.0.7 on 2020-06-16 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
