# Generated by Django 3.0.7 on 2020-06-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0002_auto_20200616_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
