# Generated by Django 3.0.7 on 2020-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_category_cat_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='image',
        ),
    ]
